spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
file:
  upload-dir: /Users/dotori/IdeaProjects/Auctionary/src/main/resources/static/uploads/